### ISSUE TITLE
#US11 Como equipo de desarrollo, quiero crear un mapa de sitio para visualizar la estructura y navegación de la aplicación web y móvil.

### ISSUE THREAD

**Issue by Andrea-Cal** [projects-ISPC/practicaProfesionalizante-ISPC#11]
- [x] #TK1: Identificar todas las páginas y secciones principales de la aplicación web y móvil.
- [x] #TK2: Organizar las páginas y secciones en un diagrama visual que muestre la estructura de navegación.

**Comment by GiulianaDeEt** [comment]
![ISPC-mapaDeSitioCORREGIDO](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/96992783/12d35bc2-ef16-47f1-986b-c2cb3d206a78)
