### ISSUE TITLE
#US19 Como miembro del equipo de desarrollo, quiero crear el diagrama de Clases para visualizar la estructura y las relaciones entre las clases del sistema.

### ISSUE THREAD

**Issue by Natalinacn** [projects-ISPC/practicaProfesionalizante-ISPC#19]
- [x] #TK01: Desarrollar el diagrama de Clases teniendo en cuenta que será adaptado en ambos proyectos (web y mobile)

**Comment by Andrea-Cal** [comment]
![Image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/106858209/ca626203-91fc-4d49-a557-1092d5478877)

Agrego Diagrama de Clases. 
Se modificaron los nombres de los métodos para unificarlos a todos en idioma inglés.
