### ISSUE TITLE
#US20 Como miembro del equipo de desarrollo, quiero agregar pantalla “contacto” para que los usuarios puedan contactar en caso de que tengan algún problema o consulta.

### ISSUE THREAD

**Issue by Natalinacn** [projects-ISPC/practicaProfesionalizante-ISPC#20]
- [x]  #TK01: Respetar las definiciones y estilos del diseño de Figma.
- [x]  #TK02: Adaptar la pantalla a responsive (móvil - tablet - escritorio).
- [x]  #TK03: Realizar tests de funcionamiento sobre la pantalla.
- [x]  #TK04: Chequear accesibilidad e implementarla en caso de que no cumpla con las normas.
- [x]  #TK05: Llamar al servicio para enviar el comentario ingresado por el usuario.
- [x]  #TK06: Asegurarse de enviar la información correcta al lado del servidor.

_! Esta US está bloqueada por #18_

**Comment by tefsantana** [comment]
### Checking de accesibilidad:

- Prueba de contraste de color (con la fuente más clara que hay en la página): 
<img src="https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/fd886be4-0c24-4128-9b6f-43dfbe6324c6" width="350" height="250">

_**Tener en cuenta que para el botón inhabilitado no es obligatorio cumplir con el contraste de color según las normas de accesibilidad.**_
- Tamaño de letra mínimo de 16px (1rem) en cualquier resolución.
- Lectura de pantalla con NVDA correcta.
- Elementos semánticos correctos.
- Navegación con teclado correcta (con soporte NVDA de remarco).
En este caso, la navegación comienza por el título y es de arriba hacia abajo izquierda a derecha, comenzando por la información y luego yendo hacia el formulario.
- Aprobación de Lighthouse:
<img src="https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/7d9da0fe-df24-4210-adb8-c2b59ae11d69" width="300" height="200">

**Comment by tefsantana** [comment]
### Evidencia de testing

Se creó un test unitario para cada uno de los componentes que conforman la página.

![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/9a502e51-7303-40c1-88d2-ea1a27ec3503)
