### ISSUE TITLE
#US23 Como miembro del equipo de desarrollo, quiero que el proyecto web cumpla con las normas básicas de accesibilidad para facilitar el acceso a todo tipo de público en igualdad de oportunidades. 

### ISSUE THREAD

**Issue by Andrea-Cal** [projects-ISPC/practicaProfesionalizante-ISPC#23]
- [x] #TK01: Incluir texto alternativo en todas las imágenes de la aplicación.
- [x] #TK02: Asegurar que el contenido de la aplicación es comprensible y de fácil acceso a los usuarios.

**Comment by tefsantana** [comment]
Se adjunta lista de pantallas por hacer accesibles:
- Registro
- Login
- Home
- Mi perfil
- Contacto
- Catálogo
- Detalle de libro
- Carrito
- Compra, paso 1
- Compra, paso 2
- Compra, paso 3
- Sobre nosotros

**Comment by tefsantana** [comment]
Pantalla Sobre Nosotros:
No necesitó de modificaciones. Se empleó Lighthouse en navegador y Axe Linter + Sonar Lint para el código.

![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/edea72ed-ee39-4d85-ace4-41c18167cc63)

**Comment by tefsantana** [comment]
Pantalla Login:
Necesito modificaciones en los modales de Login para agregar ariaDescribedBy y ariaLabelledBy al modal que se inicializa con Angular. Este cambio ya está siendo commiteado
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/8f6c8840-e1dc-4230-97c8-d4b10f0617f8)

**Comment by tefsantana** [comment]
Pantalla Registro:
Necesito modificaciones en los modales de Registro para agregar ariaDescribedBy y ariaLabelledBy al modal que se inicializa con Angular. Este cambio ya está siendo commiteado
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/3b36579a-9dce-49f3-884a-24dc208d3312)

**Comment by tefsantana** [comment]
Pantalla Home:
No necesitó modificaciones
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/bc72e53a-7a81-4ad8-bcce-5a8f209be4a6)

**Comment by tefsantana** [comment]
Pantalla mi perfil:
No necesitó modificaciones
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/53d78786-d784-4674-a258-2cd2d02318ca)

**Comment by tefsantana** [comment]
Pantalla Contacto:
No necesitó modificaciones
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/abcc3b7f-bc71-450d-b759-591c61720841)

**Comment by tefsantana** [comment]
Pantalla Catálogo:
Se necesitó modificar el color de los botones de la barra de navegación que no cumplían con la norma de contraste de color con respecto al fondo de pantalla.
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/5ea95038-99aa-4501-a925-6c1d7cc3c47c)

Al ser cambiado ahora sí cumple
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/390b9b21-68f3-4508-b130-97c2268dc4ae)

**Comment by tefsantana** [comment]
Pantalla Detalle de libro:
No necesitó modificaciones
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/36c9e060-b343-4883-8dec-0dc995c3e899)

**Comment by tefsantana** [comment]
Pantalla Carrito:
En el elemento aside es donde falla ya que el link 'Ver sucursales' tiene un color muy claro con respecto al fondo de pantalla y no cumple con la norma de accesibilidad de contraste de color.
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/e2a13083-7909-4116-ab12-89977412e8ba)

Se cambió a un color más oscuro y ahora sí cumple
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/7b3ac644-b92a-40dc-9e2a-eb73290f4d36)

**Comment by tefsantana** [comment]
Pantalla Compra (paso 1):
Se necesitó agregar el rol del multipaso para que cada ítem tenga rol de tab así también.
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/c819e65e-812d-445d-8677-800823a0f146)

Luego de la corrección se cumple las normas.

**Comment by tefsantana** [comment]
Pantalla Compra (paso 2):
Se necesitó agregar el rol del multipaso para que cada ítem tenga rol de tab así también.
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/05e71763-debb-40e0-bc3b-671426f5f26d)

Luego de la corrección se cumple las normas.

**Comment by tefsantana** [comment]
Pantalla Compra (paso 3):
Se necesitó agregar el rol del multipaso para que cada ítem tenga rol de tab así también.
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/cc2cc04f-59cf-42eb-8dc1-718cfa92c5a3)

Luego de la corrección se cumple las normas.

**Comment by tefsantana** [comment]
De esta manera se cumple que todas las pantallas sean accesibles
