### ISSUE TITLE
#US59: Como miembro del equipo de desarrollo, quiero confirmar la correcta funcionalidad del registro de usuario y login de la app móvil para detectar fallas y poder solucionarlas.

### ISSUE THREAD

**Issue by Andrea-Cal** [projects-ISPC/practicaProfesionalizante-ISPC#59]
- [x] #TK01: Crear un usuario ficticio.
- [x] #TK02: Intentar ingresar con la cuenta.
- [x] #TK03: Intentar salir de la cuenta.
- [x] #67
- [x] #TK05: Documentar cualquier error y su posible resolución.

**Comment by tefsantana** [comment]
A raíz de la cuarta tarea se ha visto que la aplicación actualmente está incumpliendo este punto ya que permite registrarse con dos emails iguales. La resolución de este bug se hará en la issue [US61](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/issues/61).

**Comment by tefsantana** [comment]
Por otro lado, las validaciones correspondientes de email y password se cumplen correctamente tanto en login como registro:

# Registro

- Validación de email
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/999d75a4-4b57-4ea6-8c11-e9c441959e8c)

- Validación de password
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/3414fe9b-9de1-4948-8d53-1ce78e53aa18)

## Post registro exitoso
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/8c7d59aa-a252-4f7f-b5ac-e85ba18b8bcc)


# Login

- Validación de email y password
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/c1f7076b-2870-4f78-aecc-ca7b832cbec2)

## Post login exitoso
![image](https://github.com/projects-ISPC/practicaProfesionalizante-ISPC/assets/83146564/1a848556-fc5d-4b13-9e2c-83799f502357)

**Comment by tefsantana** [comment]
La evidencia del bug de la TK04 se encuentra en #67
