### ISSUE TITLE
#US70: Como miembro del equipo de desarrollo, quiero testear la funcionalidad de las categorías de la app móvil  para detectar fallas y poder solucionarlas.

### ISSUE THREAD

**Issue by MDLDeveloper** [projects-ISPC/practicaProfesionalizante-ISPC#70]
- [x] #TK01: Verificar que son visibles todas las categorías.
- [x] #TK02: Comprobar que las categorías muestran los libros correctos.
- [x] #TK03: Documentar cualquier error y su posible resolución.

**Comment by Andrea-Cal** [comment]
Las categorías son visibles desde la Home Page y desde la sección Catalogo.
Los filtros por categorías no son funcionales.
